version: 0.1.0

name: first-experiment
description: This is a basic experiment leveraging the newly staff shipped GitHub Stacks feature.

branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  - name: required_approving_review_count
    description: Number of reviewers required to approve pull requests
    required: true
    default: 2
    validvalues:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6

  - name: additional_self_hosted_runner_group
    description: Name of additional self-hosted runner group to requested for GitHub Actions workflows
    validvalues:
      - Premium

configs:
  branches:
    - name: main
      parameters:
        allow-deletions: false
        allow-force-pushes: false
        enforce-admins: true
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          require-code-owner-reviews: true
          required-approving-review-count: ${{ inputs.required_approving_review_count }}
init:
  uses: "stack-init.yml"
